apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-full-stack-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube-full-stack-project
  template:
    metadata:
      labels:
        app: youtube-full-stack-project
    spec:
      containers:
        - name: youtube-full-stack-project-container
          image: devops74/youtube_project:latest
          ports:
            - containerPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-full-stack-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube-full-stack-project
  template:
    metadata:
      labels:
        app: youtube-full-stack-project
    spec:
      containers:
        - name: youtube-full-stack-project-container
          image: devops74/youtube_project:latest
          ports:
            - containerPort: 80
